import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },

  error: {
    color: "red",
    marginTop: 20,
    textAlign: "center",
    backgroundColor: "#f8d7da",
    padding: 15,
    borderRadius: 25,
    fontFamily: "Gotham-bold",
    fontSize: 18,
    width: "80%",
    alignSelf: "center",
  },

  form: {
    width: "100%",
    maxWidth: 400,
    backgroundColor: "#ffffff",
    padding: 20,
    marginTop: 10,
  },
  heading: {
    fontFamily: "Gotham-Bold",
    fontSize: 23,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
    color: "#333",
  },
  input: {
    fontFamily: "Gotham-light",
    flex: 1,
    fontSize: 16,
    color: "#3D5C54",
  },
  name: {
    fontFamily: "Gotham-light",
    fontSize: 50,
    textAlign: "left",
    color: "#fff",
  },
  bold: {
    fontWeight: "bold",
  },
  top: {
    justifyContent: "center",
    backgroundColor: "#9fbf2a",
    borderBottomLeftRadius: 20,

    paddingTop: 50,
    paddingBottom: 30,
    paddingLeft: 20,
    borderBottomRightRadius: 20,
  },
  bigX: {
    position: "absolute",
    top: 60,
    right: 10,
    padding: 10,
    zIndex: 10,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#3D5C54",
    borderRadius: 25,
    paddingVertical: 10,
    paddingHorizontal: 15,
    width: "80%",
    alignSelf: "center",
    backgroundColor: "white",
    marginBottom: 15,
  },
  icon: {
    marginRight: 10,
  },
  button: {
    backgroundColor: "#9fbf2a",
    padding: 15,
    borderRadius: 25,
    marginTop: 20,
    width: "80%",
    alignSelf: "center",
  },
  buttonText: {
    color: "#fff",
    textAlign: "center",
    fontSize: 20,
    fontFamily: "Gotham",
  },
  imagePicker: {
    alignSelf: "center",
    marginVertical: 20,
    width: 120,
    height: 120,
    borderRadius: 60,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "#ccc",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f0f0f0",
  },
  image: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  placeholder: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  placeholderText: {
    color: "#888",
    textAlign: "center",
  },
});
